[package]
name = "nutrition"
version = "0.1.0"
description = "Nutrition desktop app"
edition = "2021"

[lib]
name = "nutrition_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
app-core = { path = "../../../../crates/core" }
app-config = { path = "../../../../crates/config" }
data-client = { path = "../../../../crates/client" }
tauri = { version = "2", features = [] }
